- hosts: all
  tasks:
    - name: add hosts to inventory groups
      add_host:
        name: "{{ inventory_hostname }}"
        groups: default
      changed_when: False

- import_playbook: playbook.yml
