- name: configure ansible-pull
  hosts: all
  roles:
    - role: ansible-pull
      ansible_pull_url: git@github.com:Interaze/Node-Pool.git

- hosts: singleNode
  vars:
    - depsbuild: no
  tasks:
    - debug:
        msg: "I'm in group 'ubuntu'"
  roles:
    - role: ubuntu-install-dependencies
      when: depsbuild
    - role: ubuntu-replicate-source
    - role: ubuntu-run-environment

- hosts: upicluster
  tasks:
    - debug:
        msg: "I'm in group 'upicluster'"

- hosts: onlybar
  tasks:
    - debug:
        msg: "I'm in group 'onlybar'"

