---

- name: Install python3 pip
  become: yes
  remote_user: ubuntu
  apt:
    name: python3-pip
    state: present
    update_cache: yes
- name: Install docker python package
  remote_user: ubuntu
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose
- name: Install docker packages
  become: yes
  remote_user: ubuntu
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - linux-modules-extra-raspi
  tags:
    - docker
- name: Add Docker's official GPG key
  become: yes
  remote_user: ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker
- name: Verify that we have the key with the fingerprint
  remote_user: ubuntu
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker
- name: Set up the stable repository
  become: yes
  remote_user: ubuntu
  apt_repository:
    repo: deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present
    update_cache: yes
  tags:
    - docker
- name: Update apt packages
  become: yes
  remote_user: ubuntu
  apt:
    update_cache: yes
  tags:
    - docker
- name: Install docker
  become: yes
  remote_user: ubuntu
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  #notify: Start docker on boot
  tags:
    - docker
- name: Add remote "ubuntu" user to "docker" group
  become: yes
  remote_user: ubuntu
  user:
    name: "ubuntu"
    group: "docker"
    append: yes
  tags:
    - docker
- name: Install docker-compose
  become: yes
  remote_user: ubuntu
  get_url: 
    url : https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-aarch64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'