---

- name: Create and start services
  become: yes #todo remove
  community.docker.docker_compose:
    project_src: /home/ubuntu/source
    files:
      - single-node-compose.yml
    env_file: ~/.env
  register: output

- ansible.builtin.debug:
    var: output

- name: Run `docker-compose up` again
  become: yes #todo remove
  community.docker.docker_compose:
    project_src: /home/ubuntu/source
    files:
      - single-node-compose.yml
    env_file: ~/.env
    build: no
  register: output