---

- name: Create and start services
  community.docker.docker_compose:
    project_src: /home/ubuntu/source
    files:
      - single-node-compose.yml
  register: output

- ansible.builtin.debug:
    var: output

- name: Run `docker-compose up` again
  community.docker.docker_compose:
    project_src: /home/ubuntu/source
    files:
      - single-node-compose.yml
    build: no
  register: output