---

- name: Create and start services
#  become: yes #todo remove
  community.docker.docker_compose:
    project_src: /home/ubuntu/source
    files:
      - monitoring.yml
    env_file: ~/.env

- name: Create and start services
#  become: yes #todo remove
  community.docker.docker_compose:
    project_src: /home/ubuntu/source
    files:
      - single-node-compose.yml
    env_file: ~/.env
  register: output

- ansible.builtin.debug:
    var: output

