---

- name: Create and start services
  community.docker.docker_compose:
    project_src: source
  register: output

- ansible.builtin.debug:
    var: output

- name: Run `docker-compose up` again
  community.docker.docker_compose:
    project_src: source
    build: no
  register: output