---

- name: install units for ansible-pull
  become: yes
  template:
    dest: /etc/systemd/system
    src: "{{ item }}"
  loop:
    - ansible-pull.service
    - ansible-pull.timer

- name: enable ansible-pull timer
  become: yes
  service:
    name: ansible-pull.timer
    state: started
    daemon_reload: yes
    enabled: yes
